### ISSUE TITLE
Exercise 3 - Logistic Regression Cost Function

### ISSUE THREAD

**Issue by DOH-WLD0303** [dibgerge/ml-coursera-python-assignments#108]
Hey folks,

I've encountered an issue with the initial test of the regularized logistic regression cost function (lrCostFunction). The cell that defines the test below has the wrong values. My implementation of the lrCostFunction appears to be correct and comes back correct when sent to the grader.

The existing code is below:

```python
J, grad = lrCostFunction(theta_t, X_t, y_t, lambda_t)

print('Cost         : {:.6f}'.format(J))
print('Expected cost: 2.534819')
print('-----------------------')
print('Gradients:')
print(' [{:.6f}, {:.6f}, {:.6f}, {:.6f}]'.format(*grad))
print('Expected gradients:')
print(' [0.146561, -0.548558, 0.724722, 1.398003]');
```

This should be (based on my submission to the official grader)
```python
J, grad = lrCostFunction(theta_t, X_t, y_t, lambda_t)

print('Cost         : {:.6f}'.format(J))
print('Expected cost: 3.085728')
print('-----------------------')
print('Gradients:')
print(' [{:.6f}, {:.6f}, {:.6f}, {:.6f}]'.format(*grad))
print('Expected gradients:')
print(' [0.355376, -0.491709, 0.885979, 1.663668]');
```

**Comment by ackl** [comment]
that's very interesting, for my implementation (me i get the same results as what is expected in the print statements

```
Cost         : 2.534819
Expected cost: 2.534819
-----------------------
Gradients:
 [0.146561, -0.548558, 0.724722, 1.398003]
Expected gradients:
 [0.146561, -0.548558, 0.724722, 1.398003]
 ```
 
 it could be that you have done the unregularised version (which is indeed what is asked of you) and already tried to run the test case? notice that section 1.3.3 asks you to go back and change it to the regularised version before running the test case

**Comment by DOH-WLD0303** [comment]
@ackl, thanks for commenting. Strangely enough today when I came back to it, my results came out as expected for the given test after the lrCostFunction. Something must have gotten changed in my notebook environment by accident that a restart corrected. Notebooks are great but it's times like these that are always frustrating 😅

Thanks again for taking the time to comment!
