### ISSUE TITLE
Learning Curve Method is rejected by grader even if its true

### ISSUE THREAD

**Issue by devNaresh** [dibgerge/ml-coursera-python-assignments#18]
I am doing week 6 exercise and found that learning curve method is not accepting solution. My Linear Regression cost function is accepted but this is not.

` m = y.size

    # You need to return these values correctly
    error_train = np.zeros(m)
    error_val   = np.zeros(m)

    # ====================== YOUR CODE HERE ======================
    for i in range(1, m+1):
        X_train = X[:i, :]
        y_train = y[:i]
        theta = utils.trainLinearReg(linearRegCostFunction, X_train, y_train, lambda_)
        error_train[i-1] = linearRegCostFunction(X_train, y_train, theta, lambda_)[0]
        error_val[i-1] = linearRegCostFunction(Xval, yval, theta, lambda_)[0]
    # =============================================================
    return error_train, error_val`

I can see same graph in output.

**Comment by Andreas-Atanasiu** [comment]
Hello devNaresh,

I have the same issue. How did you solve it?

Thank you,
Andreas

**Comment by devNaresh** [comment]
yes value of lambda should be zero

**Comment by brandus1** [comment]
hi, i am facing the same problem, and setting lamba_=0 doesn't solve the grader problem.

i do also see the same graph as the exercise.

please help! thank you
