### ISSUE TITLE
Fitting Linear Regression - ex5

### ISSUE THREAD

**Issue by GioDecio** [dibgerge/ml-coursera-python-assignments#19]
Hi
Thanks for this work!

I have correctly submitted the _Regularized Linear Regression Cost Function_ and _Regularized Linear Regression Gradient_ exercises.
However, when I plot the line of best fit, instead of getting this:

![linear_fit](https://user-images.githubusercontent.com/48034183/53449769-8794a980-3a12-11e9-9b12-517814054571.png)

I get this:

![download](https://user-images.githubusercontent.com/48034183/53449826-b6ab1b00-3a12-11e9-9961-869413f9be56.png)

Consequently, when I submit _learningCurve_, I get this `ValueError: setting an array element with a sequence.`
Can't figure out why...

**Comment by Andreas-Atanasiu** [comment]
Hello GioDecio,

I don't know if this is still relevant for you, I just encountered the same problem and solved it.
To be in-line with Coursera's Code of Honor, i'll just post a hint:

Be aware that linearRegCostFunction returns 'J' and 'grad' together. 
You only need 'J' so you have to grab it.
(print the output of the function - this is how I figured it out)

Good Luck!
Andreas

**Comment by GioDecio** [comment]
Dear @Andreas-Atanasiu 
Thank You it makes perfectly sense!

**Comment by vatsalkansara2** [comment]
hi i have same problem and i still didn't understand Andreas-Atanasiu has explained. can anybody help?
