### ISSUE TITLE
Exercise 5 

### ISSUE THREAD

**Issue by dachosen1** [dibgerge/ml-coursera-python-assignments#33]
I implemented the below code for part 1.3 of exercise 5 

`def linearRegCostFunction(X, y, theta, lambda_=0.0):
    """
    Compute cost and gradient for regularized linear regression 
    with multiple variables. Computes the cost of using theta as
    the parameter for linear regression to fit the data points in X and y. 
    
    Parameters
    ----------
    X : array_like
        The dataset. Matrix with shape (m x n + 1) where m is the 
        total number of examples, and n is the number of features 
        before adding the bias term.
    
    y : array_like
        The functions values at each datapoint. A vector of
        shape (m, ).
    
    theta : array_like
        The parameters for linear regression. A vector of shape (n+1,).
    
    lambda_ : float, optional
        The regularization parameter.
    
    Returns
    -------
    J : float
        The computed cost function. 
    
    grad : array_like
        The value of the cost function gradient w.r.t theta. 
        A vector of shape (n+1, ).
    
    Instructions
    ------------
    Compute the cost and gradient of regularized linear regression for
    a particular choice of theta.
    You should set J to the cost and grad to the gradient.
    """
    # Initialize some useful values
    m = y.size # number of training examples

    # You need to return the following variables correctly 
    J = 0

    if theta is None: 
        theta = np.zeros(theta.shape)
    else: 
        theta = theta
    
    #X = np.concatenate([np.ones((m, 1)), X], axis=1)

    # ====================== YOUR CODE HERE ======================
    h = X.dot(theta)
    
    J= (1/(2*m))*np.sum(np.square(h-y)) + (lambda_/ (2*m)) *np.sum(np.square(theta[1:]))
    
    grad = (1/m)*(X.T.dot(h-y))+ (lambda_/m)*np.r_[[[0]],theta[1:].reshape(-1,1)]
    grad = grad.flatten()

    # ============================================================
    return J, grad[[0,3]]`

the above function produces the below output, which matches the correct value.

theta = np.array([1, 1])
J, grad = linearRegCostFunction(np.concatenate([np.ones((m, 1)), X], axis=1), y, theta, 1)

Gradient at theta = [1, 1]:  [-15.303016, 598.250744] 
 (this value should be about [-15.303016, 598.250744])

However,  the grade function doesn't grade the submission

**Comment by dibgerge** [comment]
Try regularization without dividing by 2m. There might be an issues with the instructions here.

Closing this for now.
