### ISSUE TITLE
Exercise 1: warmUpExercise submission

### ISSUE THREAD

**Issue by sanfordjd** [dibgerge/ml-coursera-python-assignments#36]
the function cell [4] requests the user's email address but does not request the user's token.  
after running this cell, the kernel locks up

**Comment by satsgun** [comment]
I am running into the same problem, any insight is appreciated

**Comment by nyck33** [comment]
@satsgun restart the kernel?  Reconnect or Restart and Clear Output, etc etc
Or even change kernel.  I would go through each of those one by one.  I never had this problem but if I did that is what I'd do.

**Comment by nyck33** [comment]
@satsgun  if all those fail, try using the Jupyter notebook extension in VSCode, Emacs, etc rather than opening the notebook in Jupyter Notebooks.  Also check Stackoverflow for a better answer.

**Comment by sanfordjd** [comment]
@nyck33 at least in my case, restarting the kernel didn't fix the issue.  
it also looks like it's not prompting for the authentication hash.

**Comment by nyck33** [comment]
Does it make a difference if you are logged into the course on Coursera
when you try?

**Comment by sanfordjd** [comment]
> 
> Does it make a difference if you are logged into the course on Coursera when you try?
> […](#)
> On Wed, Aug 7, 2019, 22:07 sanfordjd ***@***.***> wrote: @nyck33 <https://github.com

No. I've tried both logged in and logged-out of the Coursera course. Same result.

**Comment by dibgerge** [comment]
I cannot reproduce this. In your jupyter notebook, can you add this code in one cell, and then run it:

`def prompt_me():
     input('Input 1')
     input('Input 2')

prompt_me()
`
Does this code asks you for two inputs?

**Comment by sanfordjd** [comment]
@dibgerge : ah ha!  

user-error-ish problem ...  
I wasn't hitting the "enter" key after inputting my email address ... and I since I didn't, the second field (for the token) didn't show/ pop-up. Which explains why the kernel was just sitting there.

**Comment by satsgun** [comment]
@sanfordjd @nyck33 @dibgerge Thanks much!!
