### ISSUE TITLE
exercise1 gradientDescentMulti(), shape of theta is wrong

### ISSUE THREAD

**Issue by nyck33** [dibgerge/ml-coursera-python-assignments#37]
```
print(X.shape, theta.shape, y.shape)
print(theta)
print(X[0])
```
outputs:
```
(47, 3) (2,) (47,)
[-3.63029144  1.16636235]
[ 1.          0.13141542 -0.22609337]
```
because X had a column concatenated in an earlier cell:
```
X_norm = np.concatenate([np.ones((m, 1)), X_norm], axis=1)
```
so there is a mismatch when trying to do a dot product with a row of `X` and `theta`.  3 elements vs. 2.
Also it won't let me concatenate theta with the line below:
```
theta = np.concatenate([np.ones((m, 1)), theta], axis=1)
```

**Comment by nyck33** [comment]
```
<ipython-input-43-9bcabdbf6f18> in computeCostMulti(X, y, theta)
     33     # ======================= YOUR CODE HERE ===========================
     34     for i in range(m):
---> 35         cost += np.square(np.dot(X[i], theta) - y[i])
     36         J = cost * (1/(2*m))
     37     # ==================================================================

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)
```
That concatenation of a colum to `X` or `X_norm` breaks everything.  `computeCost` won't work now.

**Comment by nyck33** [comment]
Very weird.  I found solutions online and noticed that the gradient descent code is exactly the same for univariate and multivariate.  So I don't really understand the point of the exercise.  Anyways, isn't the univariate question actually multivariate when you consider theta_0 and theta_1 as 2 features?  I know theta_0 is just the y-intercept basis thing or whatever it is that gets a value of 1 assigned to it.  I thought there would be more of a difference in the formula and code.

**Comment by satsgun** [comment]
@nyck33 just wondering if you ran into this issue, If you did, how did you solve it
https://github.com/dibgerge/ml-coursera-python-assignments/issues/36#issuecomment-519088726

**Comment by nyck33** [comment]
solved.
