### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by datainvestor** [dibgerge/ml-coursera-python-assignments#5]
When I try to submit first excercise to the grader Im getting following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a776c0c55379> in <module>()
      3 
      4 # send the added functions to coursera grader for getting a grade on this part
----> 5 grader.grade()

~\PythonProjects\ml-coursera-python-assignments\submission.py in grade(self)
     31             parts[str(part_id)] = {'output': sprintf('%0.5f ', result)}
     32         result, response = self.request(parts)
---> 33         response = json.loads(response)
     34 
     35         # if an error was returned, print it and stop

~\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'
```

What should I do ?

**Comment by crudalex** [comment]
Can you convert the data type of response to string

**Comment by Krasaa** [comment]
I find that despite the problem, the grades is updated as usual so maybe the bug can be ignored.

**Comment by chrisadas** [comment]
I confirm the same errors with Python 3 on Ubuntu. And that grades are registered despite the error message.

**Comment by de3z1e** [comment]
See pull request #11 that I submitted suggesting a fix.

**Comment by chrisadas** [comment]
> 
> 
> See pull request #11 suggesting a fix.

That fixed it for me.

**Comment by UnnatiDhanaliya** [comment]
When I try to submit first exercise to the grader I'm getting following error:

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-d8e1dc2f1a27> in <module>
      3 
      4 # send the added functions to coursera grader for getting a grade on this part
----> 5 grader.grade()

~/project/machine_learning/ml/ml-coursera-python-assignments/submission.py in grade(self)
     28         # Evaluate the different parts of exercise
     29         parts = OrderedDict()
---> 30         for part_id, result in self:
     31             parts[str(part_id)] = {'output': sprintf('%0.5f ', result)}
     32         result, response = self.request(parts)

~/project/machine_learning/ml/ml-coursera-python-assignments/Exercise1/utils.py in __iter__(self)
     29                 # Each part has different expected arguments/different function
     30                 if part_id == 1:
---> 31                     res = func()
     32                 elif part_id == 2:
     33                     res = func(self.X1, self.Y1, np.array([0.5, -0.5]))

TypeError: 'numpy.ndarray' object is not callable

**Comment by blackhat0721** [comment]
# define the submission/grader object for this exercise
grader = utils.Grader()
AttributeError: module 'utils' has no attribute 'Grader'
