### ISSUE TITLE
The Grader files are changed and now we can't submit the assignment. PLEASE FIX ASAP

### ISSUE THREAD

**Issue by prasanna-sai** [dibgerge/ml-coursera-python-assignments#81]
Coursera added a new section which is located just before programming assignment 1 section of week 2. They have also changed the token duration and now token is going to expire in 30 minutes. 

After these updates, I am unable to submit the assignment. When I submitted the assignment, it is showing `HTTPError: HTTP Error 500: Internal Server Error` 

The entire error is below

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-5-a776c0c55379> in <module>
      3 
      4 # send the added functions to coursera grader for getting a grade on this part
----> 5 grader.grade()

~\Downloads\ML Assignments - Python\submission.py in grade(self)
     30         for part_id, result in self:
     31             parts[str(part_id)] = {'output': sprintf('%0.5f ', result)}
---> 32         result, response = self.request(parts)
     33         response = json.loads(response.decode("utf-8"))
     34 

~\Downloads\ML Assignments - Python\submission.py in request(self, parts)
     79 
     80         params = urlencode({'jsonBody': json.dumps(params)}).encode("utf-8")
---> 81         f = urlopen(self.submit_url, params)
     82         try:
     83             return 0, f.read()

C:\Program Files (x86)\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

C:\Program Files (x86)\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

C:\Program Files (x86)\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

C:\Program Files (x86)\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

C:\Program Files (x86)\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

C:\Program Files (x86)\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by Abhishek-michael** [comment]
Its the new grader system 
someone needs to look into it

**Comment by prasanna-sai** [comment]
So, We can't submit the assignments until someone fixes the issue.

**Comment by Red-Sky7** [comment]
I'm facing the same issue. It seems they updated their grader.
Hope it's fixed soon. This port is great.

**Comment by Debanjan2001** [comment]
I am facing the same problem too.

**Comment by Anshumalin** [comment]
Hope we get the fix asap .

**Comment by NourEldin-Osama** [comment]
I am facing the same problem too, Hope we get the fix asap.

**Comment by shai-2-0** [comment]
Same for me. I hope that can be fixed.

**Comment by MohamedElhadidy0019** [comment]
same error for me 
need fix ASAP please

**Comment by RynnDesmond** [comment]
Same here!!!
Kindly fix it asap, thx in advance

**Comment by andywot** [comment]
Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

**Comment by Red-Sky7** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

Can confirm it's working. Thanks a ton.

**Comment by prasanna-sai** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

**Comment by prasanna-sai** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

It is working now. Thank you very much.

**Comment by Debanjan2001** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

Thank you @andywot

**Comment by NourEldin-Osama** [comment]
Thank you @andywot 🥰😊
@dibgerge Please merge the pull request

**Comment by Abhishek-michael** [comment]
its still not working for me 
it throws the same error 
i cloned the @andywot 's branch and copy pasted earlier code for ex 2 and when i go to grade it throws same error

**Comment by andywot** [comment]
@Abhishek-michael can you show me the error?

**Comment by HVossi92** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

Thank you so much! :)

**Comment by Abhishek-michael** [comment]
> @Abhishek-michael I think I know what happened. Did you clone from the correct branch new-grader instead of master?

thank you so much 
apparently i cant clone the branch (im net to git so please bear with me)
i ended up getting the zip file and it worked

**Comment by archanfel** [comment]
> Hey guys, I just created a pull request for the new grader. If you can't wait you can just change the grader file yourself and see if it works with the new grading system.

thank you so much : )

**Comment by dibgerge** [comment]
Thank @andywot ! I have merged the new code. Closing this.
