### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by morteza-shahrabi-farahani** [dibgerge/ml-coursera-python-assignments#90]
Hello. I have a problem with running the first part of the notebook. 
Can anybody help me?
![rrergergerg](https://user-images.githubusercontent.com/55269252/129047055-23573896-b1b6-4019-a4fe-8a5279a67847.PNG)

**Comment by krishnova** [comment]
Hi, were you able to resolve this error?

**Comment by 19007361** [comment]
@morteza-shahrabi-farahani How did you resolve this? Thank you

**Comment by morteza-shahrabi-farahani** [comment]
I don't remember completely what I did. But I think I try to use Anaconda and then my problem is solved. Also, there are some other people who encounter this problem. I read their discussion and try their recommendetions.

**Comment by zizuo2050** [comment]
Hello i had this problem.. first go to command line then activate the machine_learning then install the requests and if you have issue to install it.. after the Activation of machine_learning.. write aconda install requests
